name: dependabot-patch-automerge
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  pull-requests: write


jobs:
  merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: prepare
        id: prepare
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: do
        if: ${{ steps.prepare.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --merge ${{github.event.pull_request.html_url}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
